org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
android.experimental.newDsl=false
android.newDsl=false
org.gradle.parallel=false
org.gradle.configureondemand=false
systemProp.org.gradle.internal.transforms.disableInstrumentationCaching=true
org.gradle.user.home=C:/Users/kings/.gradle-new