// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDvsBJ5WJzjJkZlzCh-4cgKArKhnBvYbfM',
    appId: '1:801889454576:web:e22b9dd912d03ab271f535',
    messagingSenderId: '801889454576',
    projectId: 'sbrai-solutions-2d455',
    authDomain: 'sbrai-solutions-2d455.firebaseapp.com',
    storageBucket: 'sbrai-solutions-2d455.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvsBJ5WJzjJkZlzCh-4cgKArKhnBvYbfM',
    appId: '1:801889454576:web:59bcc71cf73acad071f535',
    messagingSenderId: '801889454576',
    projectId: 'sbrai-solutions-2d455',
    authDomain: 'sbrai-solutions-2d455.firebaseapp.com',
    storageBucket: 'sbrai-solutions-2d455.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrjgwMzgbiL7xyqWOQrWXhh6Z1bwBJsGI',
    appId: '1:801889454576:ios:856784173fc9662b71f535',
    messagingSenderId: '801889454576',
    projectId: 'sbrai-solutions-2d455',
    storageBucket: 'sbrai-solutions-2d455.firebasestorage.app',
    iosBundleId: 'com.example.sbraiSolutions',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrjgwMzgbiL7xyqWOQrWXhh6Z1bwBJsGI',
    appId: '1:801889454576:ios:856784173fc9662b71f535',
    messagingSenderId: '801889454576',
    projectId: 'sbrai-solutions-2d455',
    storageBucket: 'sbrai-solutions-2d455.firebasestorage.app',
    iosBundleId: 'com.example.sbraiSolutions',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANVuUWS9Bjjdd_kZL8JKGSsw2K0lk9r9s',
    appId: '1:801889454576:android:ccdb7f257d97a14f71f535',
    messagingSenderId: '801889454576',
    projectId: 'sbrai-solutions-2d455',
    storageBucket: 'sbrai-solutions-2d455.firebasestorage.app',
  );

}