// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwMHXPh4C2kCg_dPxBY6KsEi-cy6mmQkQ',
    appId: '1:811602722366:web:f05e5a85305f4a70e7db6f',
    messagingSenderId: '811602722366',
    projectId: 'celz5-6bb71',
    authDomain: 'celz5-6bb71.firebaseapp.com',
    storageBucket: 'celz5-6bb71.firebasestorage.app',
    measurementId: 'G-VVN5PDZBJT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_1Xl8jx53c3WMUEoDG9zf-80OaxNzgjE',
    appId: '1:811602722366:android:2a8094fcaa908ffee7db6f',
    messagingSenderId: '811602722366',
    projectId: 'celz5-6bb71',
    storageBucket: 'celz5-6bb71.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUVNP5cw1d4_XYeao_gxvrXdyAIZ-lX4Q',
    appId: '1:811602722366:ios:395c8a9d688b4a44e7db6f',
    messagingSenderId: '811602722366',
    projectId: 'celz5-6bb71',
    storageBucket: 'celz5-6bb71.firebasestorage.app',
    iosBundleId: 'com.example.sbraiSolutions',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUVNP5cw1d4_XYeao_gxvrXdyAIZ-lX4Q',
    appId: '1:811602722366:ios:395c8a9d688b4a44e7db6f',
    messagingSenderId: '811602722366',
    projectId: 'celz5-6bb71',
    storageBucket: 'celz5-6bb71.firebasestorage.app',
    iosBundleId: 'com.example.sbraiSolutions',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDwMHXPh4C2kCg_dPxBY6KsEi-cy6mmQkQ',
    appId: '1:811602722366:web:f28da4ab7470db74e7db6f',
    messagingSenderId: '811602722366',
    projectId: 'celz5-6bb71',
    authDomain: 'celz5-6bb71.firebaseapp.com',
    storageBucket: 'celz5-6bb71.firebasestorage.app',
    measurementId: 'G-1KXZ7FXGPL',
  );
}
